# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-17 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20151103_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание книги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Author', verbose_name='Автор')),
            ],
        ),
    ]
