# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_quotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotations',
            name='text',
            field=models.TextField(verbose_name='Текст цитаты'),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название цитаты'),
        ),
    ]
