# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-21 05:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='picture',
            field=models.TextField(default=datetime.datetime(2017, 2, 21, 5, 57, 26, 20049, tzinfo=utc), verbose_name='Ссылка на картинку'),
            preserve_default=False,
        ),
    ]
