# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_videos_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Короткое описание топика')),
                ('text', models.TextField(verbose_name='Текст топика')),
                ('short', models.CharField(max_length=100, verbose_name='Приглашение')),
            ],
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='author',
        ),
        migrations.DeleteModel(
            name='Quotations',
        ),
    ]
