# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-10 09:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20170310_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='picture',
            field=models.TextField(default=datetime.datetime(2017, 3, 10, 9, 17, 0, 522661, tzinfo=utc), verbose_name='Ссылка на картинку'),
            preserve_default=False,
        ),
    ]
