# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-10 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_topics_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='picture',
            field=models.CharField(max_length=100, verbose_name='Ссылка на картинку'),
        ),
    ]
